version: '2'
services:
  visual-regression:
    build:
      context: .
      dockerfile: ./test/visual/Dockerfile
    environment:
      BASE_URL: http://frontend:3050
      BROWSERSTACK_USERNAME: ${BROWSERSTACK_USERNAME}
      BROWSERSTACK_ACCESS_KEY: ${BROWSERSTACK_ACCESS_KEY}
    volumes:
      - ./:/project
    entrypoint: dockerize -wait tcp://frontend:3050 -timeout 120s
    command: yarn test:visual
    depends_on:
      - frontend

  mock-backend:
    build: ./test/sandbox
    volumes:
      - './test/sandbox:/usr/src/app'

  redis:
    image: redis:3.2

  frontend:
    build: .
    env_file: visual-stack.env
    depends_on:
      - redis
      - mock-backend

