version: '3'
services:
  frontend:
    build:
      context: .
    ports:
      - 3001:3000
    depends_on:
      - redis
      - mock-backend
      - mock-sso
    environment:
      NODE_ENV: development
      API_ROOT: http://mock-backend:8001
      QA_HOST: http://localhost:3000
      DATA_HUB_BACKEND_ACCESS_KEY_ID: frontend-key-id
      DATA_HUB_BACKEND_SECRET_ACCESS_KEY: frontend-key
      REDIS_HOST: redis
      MOCK_SSO_ROOT: http://mock-sso:8080
      OAUTH2_TOKEN_FETCH_URL: http://mock-sso:8080/o/token
      OAUTH2_USER_PROFILE_URL: http://mock-sso:8080/api/v1/user/me
      OAUTH2_AUTH_URL: http://localhost:8080/o/authorize # Redirects user in the browser hence 'localhost'
      OAUTH2_REDIRECT_URL: http://localhost:3000/oauth/callback # Redirects user in the browser hence 'localhost'
      OAUTH2_CLIENT_SECRET: youAintSeenMyRight
      OAUTH2_CLIENT_ID: randomClientId
      OAUTH2_DEV_TOKEN: ditStaffToken
      CACHE_ASSETS: 'true'
      HELP_CENTRE_URL: https://datahub-helpcentre.london.cloudapps.digital
      HELP_CENTRE_ANNOUNCMENTS_URL: https://datahub-helpcentre.london.cloudapps.digital/updates/announcements
      HELP_CENTRE_API_FEED: https://data-hub-sandbox.getsandbox.com:443/help-centre/announcement
      HELP_CENTRE_FEED_API_TOKEN: apiToken
      SESSION_SECRET: foobarbaz
      REDIS_URL: redis://redis:6379
    volumes:
      - ./assets:/usr/src/app/assets
      - ./common:/usr/src/app/common
      - ./config:/usr/src/app/config
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
    entrypoint: dockerize -wait tcp://redis:6379 -wait tcp://mock-backend:8001 -wait tcp://mock-sso:8080 -timeout 180s
    command: yarn develop

  webpack:
    build:
      context: .
    depends_on:
      - frontend
    environment:
      - WEBPACK_ENV=prod
    volumes:
      - ./assets:/usr/src/app/assets
      - ./common:/usr/src/app/common
      - ./config:/usr/src/app/config
    command: ./node_modules/.bin/webpack --watch --watch-poll --progress

  mock-sso:
    image: quay.io/uktrade/mock-sso:latest
    environment:
      MOCK_SSO_SCOPE: data-hub:internal-front-end
      MOCK_SSO_TOKEN: ditStaffToken
      MOCK_SSO_USERNAME: ${MOCK_SSO_USERNAME}

  mock-backend:
    build:
      context: ./test/sandbox
    volumes:
      - './test/sandbox:/usr/src/app/test/sandbox'
    ports:
      - 8001:8001

  redis:
    image: redis:3.2
