version: '3'
services:
  dev-frontend:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000
      - 9230:9229
    depends_on:
      - redis
      - mock-backend
    env_file: mock-stack.env

  mock-backend:
    build:
      context: ./test/sandbox
    volumes:
      - './test/sandbox:/usr/src/app/test/sandbox'
    ports:
      - 8002:8001

  redis:
    image: redis:3.2
