version: '3'
services:
  frontend:
    build:
      context: .
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 3001:3000
      - 9230:9229
    depends_on:
      - redis
      - mock-backend
    env_file: mock-stack.env

  mock-backend:
    build: ./test/sandbox
    volumes:
      - './test/sandbox:/usr/src/app'

  redis:
    image: redis:3.2
