version: '3'
services:
  dev-frontend:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3000
      - 9230:9229
    depends_on:
      - redis
      - mock-backend
    env_file: mock-stack.env

  mock-backend:
    image: getsandbox/worker-cli:2.0.14
    volumes:
      - './test/sandbox:/base'
    command: /sandbox-worker-cli --base=/base --port=8001 --watch=true run

  redis:
    image: redis:3.2
