# This is a basic workflow to help you get started with Actions

name: dependabot-automerge

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Create the date tag
          id: date
          run: echo "tag=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
        
        - name: Read date tag
          run: |
            echo "$tag"
            echo "${{ env.tag }}"

        - name: Make branch
          uses: peterjgrainger/action-create-branch@v2.0.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            branch_name: dependencies-{{ steps.date.outputs.date }} >> $BRANCH_NAME
          with:
            branch: dependencies-${{ env.tag }}

